### ISSUE TITLE
Not working for me in Elvui 12.16

### ISSUE THREAD

**Issue by dmg2** [Vekkt/ElvUI_BuffHighlight#19]
Unable to load the plugin at all in 12.16, this is the first time I try to use the plugin, it will now show up in the elvui options menu like the rest of the other plugins I have installed. I tried disabling all addons and plugins besides elvui main, elvui options, and elvui buff highlight and it still did not appear. I have no Lua Errors either. Please help.

**Comment by broizter** [comment]
"ElvUI BuffHighlight: You are currently using class heath colors. Please disable this option in order to BuffHilight to work. (UnitFrames > General Options > Colors > Class Health"

Did you follow those instructions? According to the readme here in github it's only recommended to disable class colors but it actually seems required for the addon to load at all.

**Comment by Vekkt** [comment]
Replied to @broizter in #20 . It is actually mandatory. Initially it was not, but it turned out to be a giant mess with class colors enabled. 

Moreover I think this is not related to the issue here. Some (few) people experience this issue, which I have no ide where it can come form. Check issue #18, which seem to be a fix.
